"""initial schema: wikis, users, wiki_members, pages, page_revisions

Revision ID: 2a5df3404d20
Revises: 
Create Date: 2026-03-29 05:50:26.821920

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a5df3404d20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('wikis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('default_read_level', sa.String(length=20), nullable=False),
    sa.Column('default_edit_level', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_wikis_uuid'), 'wikis', ['uuid'], unique=True)
    op.create_table('pages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('wiki_id', sa.BigInteger(), nullable=False),
    sa.Column('namespace', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('is_redirect', sa.Boolean(), nullable=False),
    sa.Column('redirect_to', sa.String(length=500), nullable=True),
    sa.Column('current_revision_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_revision_id'], ['page_revisions.id'], name='fk_pages_current_revision', use_alter=True),
    sa.ForeignKeyConstraint(['wiki_id'], ['wikis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wiki_id', 'namespace', 'slug', name='uq_pages_wiki_ns_slug')
    )
    op.create_index(op.f('ix_pages_uuid'), 'pages', ['uuid'], unique=True)
    op.create_index(op.f('ix_pages_wiki_id'), 'pages', ['wiki_id'], unique=False)
    op.create_table('wiki_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wiki_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wiki_id'], ['wikis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wiki_id', 'user_id', name='uq_wiki_members_wiki_user')
    )
    op.create_index(op.f('ix_wiki_members_user_id'), 'wiki_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_wiki_members_wiki_id'), 'wiki_members', ['wiki_id'], unique=False)
    op.create_table('page_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('html_cache', sa.Text(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('author_ip', postgresql.INET(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'revision_number', name='uq_page_revisions_page_rev')
    )
    op.create_index(op.f('ix_page_revisions_page_id'), 'page_revisions', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_revisions_uuid'), 'page_revisions', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_revisions_uuid'), table_name='page_revisions')
    op.drop_index(op.f('ix_page_revisions_page_id'), table_name='page_revisions')
    op.drop_table('page_revisions')
    op.drop_index(op.f('ix_wiki_members_wiki_id'), table_name='wiki_members')
    op.drop_index(op.f('ix_wiki_members_user_id'), table_name='wiki_members')
    op.drop_table('wiki_members')
    op.drop_index(op.f('ix_pages_wiki_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_uuid'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_wikis_uuid'), table_name='wikis')
    op.drop_table('wikis')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
